name: mobile_recruitment_test
description: "Lodgify mobile recruitment app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  injectable: ^2.7.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.1+2
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

